"use client"

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Roboto } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import Hero from '@/components/Hero'
import Footer from '@/components/Footer'
import { store } from '@/redux/store'
import { Provider } from 'react-redux'
import { useState } from 'react'
import Cart from '@/components/Cart'


const inter = Inter({ subsets: ['latin'] })


 const metadata: Metadata = {
  title: 'Glow beauty',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

const [showCart, setShowCart] = useState(false)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
        <NavBar setShowCart={setShowCart}/>
        {showCart && <Cart setShowCart={setShowCart}/>}
        {children}
        <Footer/>
        </Provider>
        
        </body>
    </html>
  )
}
